import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useParams, Link } from 'react-router-dom'
import { useState } from 'react'
import { ArrowLeft, FileText, AlertTriangle, CheckCircle, Edit2, Save } from 'lucide-react'
import { format } from 'date-fns'
import toast from 'react-hot-toast'
import api from '@/lib/http/client'
import type { Summary } from '@/types'

export default function SummaryPage() {
  const { id } = useParams<{ id: string }>()
  const qc = useQueryClient()
  const [editing, setEditing] = useState(false)
  const [editContent, setEditContent] = useState('')

  const { data: summary, isLoading } = useQuery<Summary>({
    queryKey: ['summary', id],
    queryFn: () => api.get(`/meeting/${id}/summary`).then((r) => r.data.data),
    enabled: !!id,
    onSuccess: (d) => setEditContent(d.content),
  })

  const saveMutation = useMutation({
    mutationFn: () =>
      api.patch(`/meeting/${id}/summary`, { content: editContent }),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['summary', id] })
      setEditing(false)
      toast.success('Summary updated and correction recorded.')
    },
  })

  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <Link to={`/meetings/${id}`} className="btn-ghost p-2">
          <ArrowLeft size={18} />
        </Link>
        <div className="flex-1">
          <h1 className="page-header">Summary</h1>
          {summary && (
            <p className="text-gray-500 text-sm">
              Generated by {summary.aiModel} · {format(new Date(summary.createdAt), 'MMM d, yyyy')}
              {summary.reviewedBy && ' · Reviewed'}
            </p>
          )}
        </div>
        {summary && !editing && (
          <button onClick={() => setEditing(true)} className="btn-ghost text-xs">
            <Edit2 size={14} /> Correct
          </button>
        )}
      </div>

      {/* AI disclaimer */}
      <div className="card border-amber-500/20 bg-amber-500/5 p-4 mb-5 flex gap-3">
        <AlertTriangle size={18} className="text-amber-400 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-gray-400 leading-relaxed">
          This summary was generated by AI. Review it carefully. If it misrepresents any decision,
          use the "Correct" button above to fix it — corrections are logged for audit purposes.
        </p>
      </div>

      {isLoading ? (
        <div className="space-y-4">
          <div className="h-32 skeleton rounded-2xl" />
          <div className="h-24 skeleton rounded-2xl" />
        </div>
      ) : !summary ? (
        <div className="text-center py-24">
          <FileText size={48} className="text-gray-700 mx-auto mb-4" />
          <p className="text-gray-400">No summary available yet.</p>
          <p className="text-gray-600 text-sm mt-1">Summary is generated after transcription completes.</p>
        </div>
      ) : (
        <div className="space-y-5">
          {/* Main content */}
          <div className="card p-5">
            <h2 className="section-title">Overview</h2>
            {editing ? (
              <>
                <textarea
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  rows={10}
                  className="input-field resize-none w-full"
                />
                <div className="flex gap-3 mt-3">
                  <button onClick={() => saveMutation.mutate()}
                    disabled={saveMutation.isPending}
                    className="btn-primary text-sm">
                    {saveMutation.isPending ? <span className="spinner" /> : <><Save size={14} /> Save Correction</>}
                  </button>
                  <button onClick={() => { setEditing(false); setEditContent(summary.content) }}
                    className="btn-secondary text-sm">Cancel</button>
                </div>
              </>
            ) : (
              <p className="prose-dark whitespace-pre-wrap">{summary.content}</p>
            )}
          </div>

          {/* Key points */}
          {summary.keyPoints?.length > 0 && (
            <div className="card p-5">
              <h2 className="section-title">Key Points</h2>
              <ul className="space-y-2">
                {summary.keyPoints.map((kp, i) => (
                  <li key={i} className="flex gap-3 text-sm text-gray-300">
                    <CheckCircle size={16} className="text-green-400 flex-shrink-0 mt-0.5" />
                    {kp}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Decisions */}
          {summary.decisions?.length > 0 && (
            <div className="card p-5">
              <h2 className="section-title">Decisions Made</h2>
              <ul className="space-y-2">
                {summary.decisions.map((d, i) => (
                  <li key={i} className="flex gap-3 text-sm text-gray-300">
                    <span className="w-5 h-5 rounded-full bg-brand-600/30 text-brand-400 text-xs flex items-center justify-center flex-shrink-0 font-medium">
                      {i + 1}
                    </span>
                    {d}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {summary.correctedAt && (
            <p className="text-xs text-gray-600 text-right">
              Last corrected: {format(new Date(summary.correctedAt), 'MMM d, yyyy HH:mm')}
            </p>
          )}
        </div>
      )}
    </div>
  )
}
